# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 23:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charityapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.TextField()),
                ('picture', models.TextField()),
                ('description', models.TextField()),
                ('link', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_id', models.TextField()),
                ('transfer_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_average', models.DecimalField(decimal_places=2, max_digits=20)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('rule_creator', models.BooleanField(default=False)),
                ('threshold', models.DecimalField(decimal_places=4, max_digits=6)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charityapp.Sector')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='charity_account_id',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='rule',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charityapp.Sector'),
        ),
        migrations.AddField(
            model_name='rule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='link',
            name='sector',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='charityapp.Sector'),
        ),
        migrations.AddField(
            model_name='charity',
            name='sector',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='charityapp.Sector'),
        ),
    ]
