# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 00:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charityapp', '0002_auto_20170218_1853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charity',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ('sector',)},
        ),
        migrations.AlterModelOptions(
            name='rule',
            options={'ordering': ('sector',)},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='suggestion',
            options={'ordering': ('-threshold', 'sector', 'name')},
        ),
    ]
